#!/bin/bash

# Command line utility to create a labels for a given target path

set -e

function print_error()
{
    printf "%s\n" "$*" 1>&2
}

# Makes a label to the given target
#
# 1 = label
# 2 = target
#
function make_label()
{
    mkdir -p $1
    ln "$2" $1
}

if [ $# -eq 0 ]; then
    print_error "Usage: label <target> <label>..."
    exit 1
fi

target="$1"
shift

if [ ! -e "$target" ]; then
    print_error "target file: ${target}, does not exist"
    exit 1
fi

if [ -d "$target" ]; then
    # for each file in the target directory link inside label
    for FILE in "${target}/*"
    do
	if [ ! -d "$FILE" ]; then
	    for label in "$@"; do
		make_label "$label" "$FILE"
	    done
	fi
    done
    exit 0
fi

for label in "$@"; do
    make_label "$label" "$target"
done
